
SET(COLLECTION_PATH ${TEST_FDA_DATA_ROOT} )

MACRO(TEST_FDA_PHANTOM_DATASET MASTER_DATASET_ID DATASET_ID ROI_X ROI_Y ROI_Z ROI_DX ROI_DY ROI_DZ EXPECTED_VOLUME)

SET(COLLECTION_PATH ${TEST_FDA_DATA_ROOT} )
SET(DATASET_ROI ${TEMP}/${DATASET_ID}_ROI.mha)

EXTRACT_REGION_OF_INTEREST(${MASTER_DATASET_ID} ${DATASET_ID} ${ROI_X} ${ROI_Y} ${ROI_Z} ${ROI_DX} ${ROI_DY} ${ROI_DZ} )
GENERATE_FEATURES( ${DATASET_ID} )
SCREEN_SHOT_FEATURES(  ${DATASET_ID} 001 )
COMPUTE_SEGMENTATIONS( ${DATASET_ID} 001 ${EXPECTED_VOLUME})

ENDMACRO(TEST_FDA_PHANTOM_DATASET)


CONVERT_DICOM_TO_META( ${COLLECTION_PATH} FDA_A "6591" )

#  "raida/mag4/phantom_studies/Yamamoto-018/25ma1/3632/6591"
TEST_FDA_PHANTOM_DATASET(FDA_A FDA_A_01 
  370 250 320 
   60  50  70
  452.83
  )

TEST_FDA_PHANTOM_DATASET(FDA_A FDA_A_02 
  330 260 500 
   50  40  70
  226.01
  )

TEST_FDA_PHANTOM_DATASET(FDA_A FDA_A_03 
  320 310 120 
   30  40  70
  56.38
  )

