
MACRO(TEST_FDA_PHANTOM_DATASET MASTER_DATASET_ID DATASET_ID DATASET_DIRECTORY ROI_X ROI_Y ROI_Z ROI_DX ROI_DY ROI_DZ)

SET(COLLECTION_PATH ${TEST_FDA_DATA_ROOT} )
SET(DATASET_ROI ${TEMP}/${DATASET_ID}_ROI.mha)

CONVERT_DICOM_TO_META( ${COLLECTION_PATH} ${MASTER_DATASET_ID} ${DATASET_DIRECTORY} )
EXTRACT_REGION_OF_INTEREST(${MASTER_DATASET_ID} ${DATASET_ID} ${ROI_X} ${ROI_Y} ${ROI_Z} ${ROI_DX} ${ROI_DY} ${ROI_DZ} )
GENERATE_FEATURES( ${DATASET_ID} )
SCREEN_SHOT_FEATURES(  ${DATASET_ID} 001 )
COMPUTE_SEGMENTATIONS( ${DATASET_ID} 001 )

ENDMACRO(TEST_FDA_PHANTOM_DATASET)


TEST_FDA_PHANTOM_DATASET(FDA6591Full FDA6591 
  "raida/mag4/phantom_studies/Yamamoto-018/25ma1/3632/6591"
  100 170 180 
  100 120  64
  )

